CREATE TABLE `searchLog` (
  `seq` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '시퀀스',
  `index` VARCHAR(100) NOT NULL ,
  `keyword` VARCHAR(50) DEFAULT NULL,
  `count` INT(11) DEFAULT '0',
  `date` DATE ,
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`seq`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='searchLog'